### ISSUE TITLE
Bug: retreat

### ISSUE THREAD

**Issue by z-mehta** [h0111in/PokemonGoBack#49]
When retreating the active pokemon.........after the retreat happen, the cards donot swap , that is, the bench card is on both area,,,,,active and bench

**Comment by z-mehta** [comment]
everything is fine , except the bench card which is swapped with the active card should removed from the bench

**Comment by h0111in** [comment]
retreat bug is fixed. please check it again.

**Comment by z-mehta** [comment]
yes.......its fixed....  @h0111in  thx.
