### ISSUE TITLE
bug: retreat(when no pokemon on the bench)

### ISSUE THREAD

**Issue by z-mehta** [h0111in/PokemonGoBack#52]
retreat is working fine..........but just add a condition that, if there is no benched pokemon then retreat will be not intiated.

@h0111in  now, when i go for retreat , if there is no pokemon on bench........then game is stuck on the message box, to select card from bench during retreat

**Comment by h0111in** [comment]
yes it has been fixed.

**Comment by z-mehta** [comment]
issue fixed....thx @h0111in
