### ISSUE TITLE
Bug: evolving the pokemon

### ISSUE THREAD

**Issue by z-mehta** [h0111in/PokemonGoBack#54]
Ideally, the stage 1 pokemon is only attack to the respective basic pokemon..................to evolve the pokemon.

@h0111in but in our game, the stage 1 pokemon can be attached to any basic pokemon card.

it should be only attached to the respective basic pokemon

**Comment by h0111in** [comment]
it is already done.

**Comment by z-mehta** [comment]
its fixed........... @h0111in thx
